language: go
go:
  - 1.3
  - 1.4
  - 1.5
sudo: false
services:
  - memcache # github.com/revel/revel/cache
  - redis-server
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - export REVEL_BRANCH="develop"
  - 'if [[ "$TRAVIS_BRANCH" == "master" ]]; then export REVEL_BRANCH="master"; fi'
  - 'echo "Travis branch: $TRAVIS_BRANCH, Revel dependency branch: $REVEL_BRANCH"'
  - go get -v github.com/revel/revel/...
  - git clone -b $REVEL_BRANCH git://github.com/revel/modules ../modules/
  - git clone -b $REVEL_BRANCH git://github.com/revel/cmd ../cmd/
  - git clone git://github.com/revel/samples ../samples/
  - go get -v github.com/revel/cmd/revel
script:
  - go test github.com/revel/revel...

  # Ensure the new-app flow works (plus the other commands).
  - revel new     my/testapp
  - revel test    my/testapp
  - revel clean   my/testapp
  - revel build   my/testapp build/testapp
  - revel package my/testapp

  # Build & run the sample apps
  - revel test github.com/revel/samples/booking
  - revel test github.com/revel/samples/chat
  - revel test github.com/revel/samples/facebook-oauth2
  - revel test github.com/revel/samples/twitter-oauth
  - revel test github.com/revel/samples/validation
  - revel test github.com/revel/samples/persona
  - revel test github.com/revel/samples/upload
